name: Build and Publish Docker

on:
  schedule:
    # Rust tends to make stable releases every six weeks on Thursday 10am
    # Pacific Time. Force a build a few hours later than that (every week) to
    # scoop up the newest stable and beta (including patch releases).
    #
    # This way, even if we don't update the matrix below we should still have
    # images.
    - cron: '15 9 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rust-musl-builder

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          file: ./Dockerfile
          build-args: |
            TOOLCHAIN='stable'



